#!/usr/bin/env zsh

script_dir=${0:A:h}

if [[ ! -d ${script_dir}/null ]]; then
    echo "Minion doesn't appear to be in process of an update."
    exit 0
fi

cd ${script_dir}

echo "Finishing update..."

mv null/Minion-jfx.jar .
mv null/lib/ ./lib/*
rm -r null

echo "Done!"

